# address=/ghcr.io/140.82.121.34
# address=/github.com/140.82.121.3
bogus-priv
cache-size=1000000
# address=/poems.codes/127.0.0.1
conf-file=/etc/dnsmasq.0000312e7c60b13f7d00037e80110160.conf
conf-file=/etc/dnsmasq.007d8304b493-030315b480037e80110013.conf
conf-file=/etc/dnsmasq.07e80a212e0704.conf
domain-needed
expand-hosts
log-queries
log-debug
log-facility=/var/log/dnsmasq.log
# no-poll
# no-resolv
server=8.8.4.4
server=1.1.1.1
server=8.8.8.8
strict-order
